using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Quartz.netByExample.Jobs
{
    [PersistJobDataAfterExecution]
    [DisallowConcurrentExecution]
    public class BadJob2: IJob
    {
        public void Execute(IJobExecutionContext context)
        {
            JobKey jobKey = context.JobDetail.Key;
            Console.WriteLine("---{0} executing at {1}", jobKey, DateTime.Now.ToString("r"));

            // a contrived example of an exception that
            // will be generated by this job due to a 
            // divide by zero error
            try
            {
                int zero = 0;
                int calculation = 4815 / zero;
            }
            catch (Exception e)
            {
                Console.WriteLine("--- Error in job!");
                JobExecutionException e2 = new JobExecutionException(e);
                // Quartz will automatically unschedule
                // all triggers associated with this job
                // so that it does not run again
                e2.UnscheduleAllTriggers = true;
                throw e2;
            }

            Console.WriteLine("---{0} completed at {1}", jobKey, DateTime.Now.ToString("r"));
        }
    }
}
